server:
    hostname: 127.0.0.1
    port: 3435

database:
    hostname: host.docker.internal
    port: 5432
    user: postgres
    password: password
    sslMode: false
    timeZone: Asia/Shanghai

Authorization:
    # Generate a random secret-key by the following shell:
    # $ echo $(dd if=/dev/urandom | base64 -w0 | dd bs=1 count=20 2>/dev/null)
    secret-key: XWpHQ0Q1fUM3H8M3ysmk
    refresh-secret-key: tuiBz7zIUQYKii+ncBdt

qiniu:
  cdn_url: 
  access_key: 
  secret_key: 
  bucket: 

openai:
    api-token: sk-xxx
    model: gpt-3.5-turbo-16k
    proxy-url: https://api.closeai-proxy.xyz/v1/chat/completions
    time-out: 60
    prompt: 我是一名阿尔兹海默症患者，请根据以下内容，回答我提出的问题，如果在下面内容中找不到相关信息，请回答不知道：

